version: "3.6"
services:
    server:
        image: ugractf/infinitejumps
        build:
            context: ./private
            dockerfile: Dockerfile
        ports:
            - 31337
        restart: always
