category:   reverse
points:     350
short:      hackedjumps
name:       "Infinite Jumps III: Banned Hacker"
author:     "pirotexnic27, nsychev"
description: >
    Оказывается, что Пётр Пывнер делает не только малварь, 
    но и игры, которые пользуются популярностью, правда недавно
    одну из его игр по какой-то причине удалили из магазинов. 
    Мы успели сохранить одну из версий, но не смогли найти 
    ничего подозрительного. 
    
    Разумеется, игру пытались взломать много раз. Говорят, что 
    у одного игрока это получилось неудачно и все его достижения
    аннулировали. Скажите, как его зовут?
    
    *В этом таске нужно сдавать флаг 3*
url: https://yadi.sk/d/gQSLKnF63Ws7xq
flags:
  -
    text:   "ugra_flag3_tr4shy_f3tch_ta5k"